### ISSUE TITLE
Does not seem to work on linebreaks

### ISSUE THREAD

**Issue by amenk** [eduardokum/laravel-mail-auto-embed#11]
If you have HTML like

     <img 
             src="foo.jpg"
     >

it does not seem to work

**Comment by eduardokum** [comment]
Hello, i made some changes (22b2aa7a302c879b7c34e5629253036a3a0ba720)

can you see if works fine?

In my tests worked very well

**Comment by eduardokum** [comment]
Hello,

I made some changes (f19677a87b0d900c0c90671e34b38ac525189bf9)

Can you see If they works fine?

In my tests works very well.

**Comment by amenk** [comment]
Thank you
