### ISSUE TITLE
Not working in Job

### ISSUE THREAD

**Issue by theupriser** [eduardokum/laravel-mail-auto-embed#12]
Hello, 

First of all super cool swiftmailer plugin! works like a charm when sending mails without queueing them. So thats also my problem.
I'm queueing my mails because I have a daily limit.

What I discovered is that when the queue mailer job sends the mails with this command:
`Mail::send($email)` 

It does not convert the urls in the view to attachments, it only does when I call the above command in a controller.

Thanks in advance!

**Comment by eduardokum** [comment]
Hello, this can be the variable url within `config/app.php`. When you run in the background you need to check the return of your `url()` function.

I use in queue too and not have trouble.

**Comment by vogelor** [comment]
Having the same problem. 
using $this->user->notify( $this->notification ); in the job.
the img will not be replaced. 
maybe you can give me some starting points to debug. than i may help you find the error

**Comment by vogelor** [comment]
i got the problem.
my image is NOT available in the public folder. it is available with a route. 
so in your embedder: 
if (!file_exists($filePath)) is TRUE because there is no file at all.

**Comment by theupriser** [comment]
It has been solved.. but still don't know why. Maybe a restart of my redis server, I can't exactly remember.

**Comment by MichalKrakow** [comment]
I would say it's not working at all with laravel 5.5.45. Zero luck debugging also.

**Comment by clytras** [comment]
It's working after restarting Horizon.
Always remember to restart the queue running service after installing new packages and also after making changes to the code.
