### ISSUE TITLE
Working with images from url without public-dir

### ISSUE THREAD

**Issue by vogelor** [eduardokum/laravel-mail-auto-embed#13]
i changed your Embedder so that it can handle image from a remote host. Maybe you want to add the code to your great project...
	/**
	 * @param  string $url
	 *
	 * @return string
	 */
	public function fromUrl( $url ) {
		$filePath = str_replace( url( '/' ), public_path( '/' ), $url );

		if ( ! file_exists( $filePath ) ) {
			$ch = curl_init( $url );
			curl_setopt( $ch, CURLOPT_HEADER, 0 );
			curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1 );
			curl_setopt( $ch, CURLOPT_BINARYTRANSFER, 1 );
			/*
			 * Maybe this should be a config beacuase of the security risk...
			 */
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

			$raw         = curl_exec( $ch );
			$httpcode    = curl_getinfo( $ch, CURLINFO_HTTP_CODE );
			$contentType = curl_getinfo( $ch, CURLINFO_CONTENT_TYPE );
			/* Only for debugging */
			//$error = curl_error($ch);
			curl_close( $ch );
			if ( $httpcode == 200 ) {
				return $this->base64String( $contentType, $raw );
			}

			return $url;
		}

		return $this->base64String( mime_content_type( $filePath ), file_get_contents( $filePath ) );
	}

**Comment by vogelor** [comment]
Here is the code for the Attachmentembedder:
    /**
     * @param  string  $url
     */
    public function fromUrl($url)
    {
        $filePath = str_replace(url('/'), public_path('/'), $url);

        if (!file_exists($filePath)) {
	        $ch = curl_init( $url );
	        curl_setopt( $ch, CURLOPT_HEADER, 0 );
	        curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1 );
	        curl_setopt( $ch, CURLOPT_BINARYTRANSFER, 1 );
	        /*
			 * Maybe this should be a config beacuase of the security risk...
			 */
	        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
	        $raw         = curl_exec( $ch );
	        $httpcode    = curl_getinfo( $ch, CURLINFO_HTTP_CODE );
	        $contentType = curl_getinfo( $ch, CURLINFO_CONTENT_TYPE );
	        /* Only for debugging */
	        //$error = curl_error($ch);
	        curl_close( $ch );
	        if ( $httpcode == 200 ) {
		        return $this->embed(
			        new Swift_Image($raw, null, $contentType)
		        );
	        }

            return $url;
        }

        return $this->embed(
            Swift_Image::fromPath($filePath)
        );
    }

**Comment by eduardokum** [comment]
Thanks, I will.

**Comment by cosmin84** [comment]
Hello, Eduardo. Are you going to merge this pull request? Would be really nice to handle remote images as well. Right now I'm definitely in need of this feature :)

**Comment by eduardokum** [comment]
I cannot merge this, it changes all namespaces.

I put the part that embed from url.
