### ISSUE TITLE
Other attributes must follow url attribute

### ISSUE THREAD

**Issue by EcoFreak** [eduardokum/laravel-mail-auto-embed#15]
Hello,

First things first... this helped me out greatly 👍 
Initially I was struggling with the image size in Outlook and after some digging I discover that the expression used in **preg_replace_callback** function call only takes into account (in the regex match group) attributes that are defined after the src attribute.
```
$html_body = preg_replace_callback('/<img.*src="(.*?)"\s?(.*)?>/', [$this, 'replaceCallback'], $html_body);
```

This is really not a huge problem but I still wasted some time find this out so I would suggest either one of two things:
1. Change the regex to include attributes both before and after the src attribute;
2. Update the docs to include this notice.

I wouldn't mind helping if you would like me to.
Thoughts?

Thanks 

H

**Comment by roelofr** [comment]
I encountered this too, so I fixed it in #18

**Comment by roelofr** [comment]
As #18 has been merged, this is no longer a problem on `dev-master`. 

A tag should at some point appear, I guess.

**Comment by eduardokum** [comment]
Thanks for all, i will make a new tag
