### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MichalKrakow** [eduardokum/laravel-mail-auto-embed#20]
Just after digging into AttachmentEmbedder.php i found out that files must be served from public folder... 
```
$filePath = str_replace(url('/'), public_path('/'), $url);
```
this would be like the first thing to include in the documentation.

**Comment by eduardokum** [comment]
This is if using url, if using the url is obviously that need be public.

I'll be warning this in the documentation to be clearer

Thanks
