### ISSUE TITLE
Crashes on specific attachment

### ISSUE THREAD

**Issue by gwleuverink** [eduardokum/laravel-mail-auto-embed#26]
Hi there! Thanks for the package, it has been very useful to me.

I am encountering a situation where the auto embed fails with the following message:

`file_exists(): Unable to find the wrapper "content"`

You can find the stack trace here: https://flareapp.io/share/x5MEkb5k#F38

The value of $filePath is `content://com.samsung.android.email.attachmentprovider/1/6796/RAW`

For most other emails this works without a hitch. Can anyone think of a reason why this fails?

Any help is greatly appreciated!

**Comment by eduardokum** [comment]
Try run this on your tinker 

$filePath = str_replace(url('/'), public_path('/'), 'content://com.samsung.android.email.attachmentprovider/1/6796/RAW');

I thinks this will return null, because the class try to use the file who you have locally
