### ISSUE TITLE
Not working when using different mail driver

### ISSUE THREAD

**Issue by riaanlom** [eduardokum/laravel-mail-auto-embed#44]
If you send an email using a different mail driver other than default, the plugin is not registered and images are not embeded. 

I have to manually register the plugin in my AppServiceProvider boot method for each mail driver I use:

`
Mail::driver('sendgrid')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));`
`Mail::driver('mailgun')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));`
`Mail::driver('gmail')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));
`

Perhaps put a loop in your ServiceProvider to register the plugin for each mail driver.

**Comment by SUXUMI** [comment]
Actually, I've the same issue and some other issues:

For me, including above mentioned, does not work:
```
2. ![product](full-url)
3. <img src="(full-url)" data-auto-embed="base64">
```

but works:
```
1. <img src="(full-url)">
2. <img src="(full-url)" data-auto-embed="attachment">
```

Also, I'm using v1.0.4, can't install the latest v1.0.5 as it conflicts with Laravel 8.5* 's default packages.

Dear @riaanlom thanks for the mentioned solution!

Dear @eduardokum , Great package! (just need some fixes)

**Comment by fadedshadowx** [comment]
> If you send an email using a different mail driver other than default, the plugin is not registered and images are not embeded.
> 
> I have to manually register the plugin in my AppServiceProvider boot method for each mail driver I use:
> 
> ` Mail::driver('sendgrid')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));` `Mail::driver('mailgun')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));` `Mail::driver('gmail')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed'))); `
> 
> Perhaps put a loop in your ServiceProvider to register the plugin for each mail driver.

I am currently using smtp driver and this method does not work. Do you know maybe a working method?

**Comment by eduardokum** [comment]
> If you send an email using a different mail driver other than default, the plugin is not registered and images are not embeded.
> 
> I have to manually register the plugin in my AppServiceProvider boot method for each mail driver I use:
> 
> ` Mail::driver('sendgrid')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));` `Mail::driver('mailgun')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed')));` `Mail::driver('gmail')->getSwiftMailer()->registerPlugin(new SwiftEmbedImages($this->app['config']->get('mail-auto-embed'))); `
> 
> Perhaps put a loop in your ServiceProvider to register the plugin for each mail driver.

I made this loop in this push 4620ffd20742ec369020d09fc50cac9a007e61c9 see if this solves your problem
