### ISSUE TITLE
Migrate to Symfony Mailer (Laravel 9)

### ISSUE THREAD

**Issue by henryavila** [eduardokum/laravel-mail-auto-embed#45]
SwiftMailer is no longer maintained as of December 2021. It's moved to Symfony Mailer. Laravel 9 uses Symfony Mailer now.

Please, move SwiftMailer to Symfony Mailer for security and update

**Comment by jamespavett** [comment]
Yea could this be looked into? Currently unusable with Laravel 9.

**Comment by eduardokum** [comment]
I put support on the develop branch, if you can test it too
