### ISSUE TITLE
Images Not Loading on Laravel 8

### ISSUE THREAD

**Issue by jamespavett** [eduardokum/laravel-mail-auto-embed#46]
Hello,

I have just tried upgrading the package from release 1.0.4 to 1.0.6 and images are not appearing. I was unable to test on 1.0.5 due to package conflicts.

Laravel version is 8.79.0

In my blade file I define the following, which has always worked (shows three logos side by side):

```
<tr>
    <td class="header">
        <div style="width: 100%; text-align:center">
            <table style="margin: 0 auto; width: 80%">
                <tr>
                    <td class="column" style="text-align:center">
                        <img alt="Logo 1"
                             src="{{ config('app.url') . '/images/logo1.png' }}">
                    </td>
                    <td class="column" style="text-align:center; padding: 0 50px">
                        <img alt="Logo 2"
                             src="{{ config('app.url') . '/images/logo2.png' }}">
                    </td>
                    <td class="column" style="text-align:center">
                        <img alt="Logo 3" src="{{ config('app.url') . '/images/logo3.png' }}">
                    </td>
                </tr>
            </table>
        </div>
    </td>
</tr>
```

After upgrading to 1.0.6, I get the following output:

![image](https://user-images.githubusercontent.com/10764464/156600989-38af9df8-c1a6-45a1-a640-cefde81452ff.png)

But I can still see that the src on the images has been updated.

![image](https://user-images.githubusercontent.com/10764464/156601114-a4b9e2be-abba-4a97-97fa-b431b7ed3ae9.png)

Has anything significant changed in the package, or am I doing something incorrect?

**Comment by pixelplant** [comment]
@jamespavett indeed having the same issue in the latest L8 framework version 8.83.3, images are gone

**Comment by pixelplant** [comment]
cid code is there but the swift container with the image data is missing

**Comment by pixelplant** [comment]
the quick solution was to disable embeding for the moment MAIL_AUTO_EMBED=false

**Comment by pixelplant** [comment]
downgrading to 1.0.4 seems to make it work again. We'll probably need to fork 1.0.4 if we need php8 support though.
My bet is the issue comes from the package "masterminds/html5" which is not used on 1.0.4 but only on recent versions of laravel-mail-auto-embed. I get cids for the images but not the attachment of the actual image data so my bet is that this new html parser has some bugs in all versions or at least the recent one (275)

**Comment by padre** [comment]
@jamespavett I have the same issue

@pixelplant Thanks!

**Comment by eduardokum** [comment]
I fixed it in version 1.0.7, if you can test it too

**Comment by pixelplant** [comment]
@eduardokum thanks, tested it and it works fine now

**Comment by jamespavett** [comment]
Thank you!
