### ISSUE TITLE
Possibility to set max timeout for remote urls

### ISSUE THREAD

**Issue by kl4ver** [eduardokum/laravel-mail-auto-embed#49]
When sending mails in a loop, curl can freeze.
Would it be an option to define a timeout option in the config file?

**Comment by ankurk91** [comment]
Dear package author:

Why dont you use Laravel's inbuilt HTTP client?

**Comment by eduardokum** [comment]
> When sending mails in a loop, curl can freeze. Would it be an option to define a timeout option in the config file?

I made this change in this push 4620ffd20742ec369020d09fc50cac9a007e61c9 see if that's what I was talking about

> Dear package author:
> 
> Why dont you use Laravel's inbuilt HTTP client?

When the package was made there was no such option.
