### ISSUE TITLE
Suggestion: Add optional caching to prevent doing unnecessary requests

### ISSUE THREAD

**Issue by baaskoen** [eduardokum/laravel-mail-auto-embed#53]
**Description**

If I understand correctly, a CURL request will be performed on every image (as seen here: https://github.com/eduardokum/laravel-mail-auto-embed/blob/master/src/Embedder/AttachmentEmbedder.php#L102).

This could potentially be problematic if you send a lot of e-mails subsequently.

**Suggestion**

Add a config option (defaults to `false`) that will cache images for a certain duration by using the Laravel `Cache` facade.

**Comment by eduardokum** [comment]
Nice! I put this on master, I will some tests before create a tag.

https://github.com/eduardokum/laravel-mail-auto-embed/commit/e41a4b658505bc59910dd14835370631f8211b64
